### ISSUE TITLE
Integrate with Database

### ISSUE THREAD

**Issue by g-anupam** [acmpesuecc/Movie-Booking-CLI#1]
As of now the code uses a file called data.csv to keep track of previous bookings. This however is not practical in a real life scenario. 

Instead move the complete system into a database - server system in which the main code integrates with a database to perform CRUD operations. Conditions to be met for resolving the issue: 
- Transfer the entire storage system into a database system.
- Make sure to track each User created as well the different bookings that were created. You could use a table for each different movie if you like , or have one common table for all movies. You will need a separate table however for recording every new user. 
- Once the Database system is created, you will have to integrate it onto the main code in such a way that the Enter Details function, display details function, book tickets, and generate bills all rely on this database for the information. 

Partial points may be given if you were able to achieve some of them, but not all.

**Comment by AdvaySanketi** [comment]
can I get this assigned?

**Comment by Ruchavw** [comment]
please assign this issue to me

**Comment by Ruchavw** [comment]
please assign this issue to me

**Comment by g-anupam** [comment]
!assign @AdvaySanketi

**Comment by Ruchavw** [comment]
please give me some time, I am going for dinner

**Comment by g-anupam** [comment]
Make a PR and show your current progress

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @Ruchavw

**Comment by g-anupam** [comment]
Hey you have 45 mins from now. Please make a PR within that time and show your progress. Doesn't matter if you have completed it or not. I would like to track your progress.

**Comment by g-anupam** [comment]
Please make sure that you do make a PR before your timer ends. Once your timer has ended i will assign it to the next user

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
If anyone else wants to work on it do message

**Comment by AdvaySanketi** [comment]
@g-anupam Assign me this issue
Thank you

**Comment by g-anupam** [comment]
!assign @AdvaySanketi

**Comment by g-anupam** [comment]
Have you already been assigned an issue. If yes you cant work on another.

**Comment by Ayush-jk** [comment]
pls assign

**Comment by g-anupam** [comment]
!assign @Ayush-jk

**Comment by g-anupam** [comment]
!extend 120

**Comment by g-anupam** [comment]
!assign @Ayush-jk 120

**Comment by g-anupam** [comment]
!deassign

**Comment by deesha292005** [comment]
could you assign it to me!!

**Comment by g-anupam** [comment]
!extend 30

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @Ayush-jk

**Comment by g-anupam** [comment]
@Ayush-jk Please make a PR and show Progress within 45 mins

**Comment by AdvaySanketi** [comment]
Hey can you assign this issue to me

**Comment by g-anupam** [comment]
!deassign @Ayush-jk

**Comment by g-anupam** [comment]
!assign @Ayush-jk 120

**Comment by aniruddhajoshi100** [comment]
@g-anupam can I get this assigned?

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @aniruddhajoshi100

**Comment by g-anupam** [comment]
!extend 45

**Comment by g-anupam** [comment]
!assign @aniruddhajoshi100 120

**Comment by g-anupam** [comment]
!deassign @aniruddhajoshi100

**Comment by g-anupam** [comment]
Issue closed
