### ISSUE TITLE
File Handling Fix

### ISSUE THREAD

**Issue by g-anupam** [acmpesuecc/Movie-Booking-CLI#2]
As of right now, the project uses a data.csv file to check which seats are booked, and assign seats accordingly.
However certain things you might observe when you inspect the code is that we are not writing onto data.csv for any new user created. Nor is the new booking saved onto it for future purchases.

To resolve the issue, kindly fix the code so that whenever a new user is created, it is appended onto data.csv, and a subsequent movie booking should be associated to that person.
Another thing to keep note of is that change should be permanent. It means that if a new user is created in one run of the code, even after exiting it and opening the next time, that seat should be booked and data.csv should have been appended.

**Comment by jhalak-n** [comment]
hi can you assign this to me?

**Comment by Ayush-jk** [comment]
please assign

**Comment by stealthwhizz** [comment]
can i get this ?

**Comment by Ruchavw** [comment]
can you assign this please

**Comment by g-anupam** [comment]
!assign @jhalak-n

**Comment by jhalak-n** [comment]
leaving for dinner

**Comment by g-anupam** [comment]
Ok do make a PR and show your progress so far

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @jhalak-n

**Comment by g-anupam** [comment]
Hey you have 45 mins from now. Please make a PR within that time and show your progress. Doesn't matter if you have completed it or not. I would like to track your progress.

**Comment by g-anupam** [comment]
Please make sure that you do make a PR before your timer ends. Once your timer has ended i will assign it to the next user

**Comment by RisuKumari11** [comment]
can i be assigned this

**Comment by g-anupam** [comment]
Make sure that you do make a PR before the timer runs out. If not i will reassign this issue.

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @jhalak-n

**Comment by g-anupam** [comment]
!extend

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @jhalak-n

**Comment by g-anupam** [comment]
!extend

**Comment by g-anupam** [comment]
!extend 30

**Comment by g-anupam** [comment]
!extend 30

**Comment by g-anupam** [comment]
@jhalak-n Please give a PR to show your progress. Otherwise you can move on to another issue

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by Gunika-Goel** [comment]
can i be assigned please?

**Comment by amankhandelwaal** [comment]
hi, assign please

**Comment by Ruchavw** [comment]
can i get assigned please?

**Comment by avinaldo22** [comment]
can you assign this to me?

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
assign @Git-Cat-21 100

**Comment by g-anupam** [comment]
!assign @Git-Cat-21 100

**Comment by g-anupam** [comment]
!assign @Gunika-Goel 100

**Comment by g-anupam** [comment]
!assign @amankhandelwaal 100

**Comment by AkshayaR11** [comment]
can i get assigned to this??

**Comment by Anirudh10070** [comment]
please assign this to me

**Comment by Git-Cat-21** [comment]
please assign it to me

**Comment by g-anupam** [comment]
@amankhandelwaal  Please make a PR To show progress

**Comment by amankhandelwaal** [comment]
@g-anupam can you please re-assign just a lil more time?

**Comment by AyushChakraborty** [comment]
@g-anupam please assign this to me

**Comment by amankhandelwaal** [comment]
@g-anupam check my pr please

**Comment by g-anupam** [comment]
Checking now

**Comment by AutisticCoder-9000** [comment]
Hello. Can I have this task assigned to me?

**Comment by g-anupam** [comment]
This Issue is now completed!

**Comment by g-anupam** [comment]
!deassign @amankhandelwaal
