### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by g-anupam** [acmpesuecc/Movie-Booking-CLI#3]
Currently everything is in one single main.c file. This is not at all efficient and readable. Refactor the codes to suitable handler files, main files etc. Write a makefile to run the program. Also provide suitable comments for each of those functions when required.

An Extra 20 brownie points are up for grab if you are able to shorten the biggest function and make it much more efficient.

**Comment by noobieeeeeee** [comment]
I would like to be assigned to this.

**Comment by g-anupam** [comment]
!assign @noobieeeeeee

**Comment by g-anupam** [comment]
Make a PR and show your progress

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @noobieeeeeee

**Comment by g-anupam** [comment]
Hey you have 45 mins from now. Please make a PR within that time and show your progress. Doesn't matter if you have completed it or not. I would like to track your progress.

**Comment by madhavkbinoy** [comment]
can this be assigned to me ?

**Comment by g-anupam** [comment]
!extend

**Comment by g-anupam** [comment]
!extend 30

**Comment by noobieeeeeee** [comment]
Can you extend the timer by 15 minutes? PLEASE

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @noobieeeeeee

**Comment by kdb04** [comment]
can i be assigned?

**Comment by g-anupam** [comment]
This issue is completed!

**Comment by g-anupam** [comment]
Closed

**Comment by g-anupam** [comment]
!deassign

**Comment by bwaklog** [comment]
!deassign
