### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by g-anupam** [acmpesuecc/Movie-Booking-CLI#4]
You are at complete freedom to change the UI however you want to try and make it as Fancy as possible. There is absolutely no limitation to this. The bounty on this task will be 500, however 500 will be awarded only for the finest of UI advancements made. 

You are free to change this from a CLI itself, if you want to :)

Enjoy Hacking!

**Comment by SamridhiShreyaa** [comment]
can i be assigned ?

**Comment by gma4040** [comment]
please assign this to me

**Comment by g-anupam** [comment]
!assign @SamridhiShreyaa

**Comment by SamridhiShreyaa** [comment]
going for dinner! give me time

**Comment by g-anupam** [comment]
Make a PR and show your current progress

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @SamridhiShreyaa

**Comment by g-anupam** [comment]
Hey you have 45 mins from now. Please make a PR within that time and show your progress. Doesn't matter if you have completed it or not. I would like to track your progress.

**Comment by Neonishh** [comment]
can you assign this to me?

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @Neonishh

**Comment by g-anupam** [comment]
@Neonishh You now have 45 mins

**Comment by g-anupam** [comment]
@Neonishh Make a PR to show Progress

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
Anybody wants to attempt it can comment!

**Comment by unrelatedchase34** [comment]
assign me

**Comment by avinaldo22** [comment]
Pls assign

**Comment by g-anupam** [comment]
!assign @unrelatedchase34

**Comment by g-anupam** [comment]
!assign @avinaldo22

**Comment by g-anupam** [comment]
@unrelatedchase34 @avinaldo22 Check if you guys are already assigned into anything else

**Comment by noobieeeeeee** [comment]
Please Assign this to me!

**Comment by g-anupam** [comment]
!assign @ noobieeeeeee

**Comment by g-anupam** [comment]
!assign @noibieeeeeee 120

**Comment by noobieeeeeee** [comment]
typo pls correct

**Comment by g-anupam** [comment]
!assign @noobieeeeeee 120

**Comment by bwaklog** [comment]
!assign @noobieeeeeee 120

**Comment by Gunika-Goel** [comment]
Can i be assigned please?

**Comment by bwaklog** [comment]
!assign @noobieeeeeee

**Comment by g-anupam** [comment]
@noobieeeeeee There is an issue with your account. We are working on it. Meanwhile if you are not assigned to anything else you are free to work on this and make a PR to show progress

**Comment by bwaklog** [comment]
!deassign

**Comment by bwaklog** [comment]
!assign @noobieeeeeee 100

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
This assignment is now free

**Comment by g-anupam** [comment]
!deassign

**Comment by Salma-101** [comment]
can i get assigned to this?

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @Salma-101 100

**Comment by g-anupam** [comment]
@Salma-101 If you are not assigned anything else and want to take this up you can work on it. Do update your progress in a PR by 3 45 AM

**Comment by g-anupam** [comment]
Please reply if you are taking it up

**Comment by Salma-101** [comment]
yes working on it

**Comment by Salma-101** [comment]
Creating a PR now

**Comment by avinaldo22** [comment]
Can you assign this to me??

**Comment by g-anupam** [comment]
@Salma-101 Please make a PR to show progress

**Comment by Salma-101** [comment]
Yep just made

**Comment by Lalith2907** [comment]
can you pls assign me this if it hasnt been completed

**Comment by g-anupam** [comment]
!deassign

**Comment by g-anupam** [comment]
!assign @Lalith2907 90

**Comment by AyushChakraborty** [comment]
please assign if not completed

**Comment by g-anupam** [comment]
@Lalith2907 Send PR show Progress

**Comment by g-anupam** [comment]
!extend 30

**Comment by g-anupam** [comment]
! deassign @Lalith2907

**Comment by g-anupam** [comment]
!assign @Lalith2907 120

**Comment by g-anupam** [comment]
Issue Close. Lalith If you want you can make PR to get points.

**Comment by g-anupam** [comment]
!deassign @Lalith2907
